Add common Maven build workflow
codehaus-plexus/.github pull request #1
Opened 2021-10-10 18:37 UTC by plamentotev

Testing with the latest version of version requires regular update to all Plexus repositories' GitHub Actions workflows. This is a repetitive, time consuming task.

Given that the build workflow for the various Plexus project is almost the same, we can re-use common workflow. Then using the latest version of Java is just a matter of changing the build matrix in single file.

This proposal makes use of the new reusable workflows feature - https://docs.github.com/en/actions/learn-github-actions/reusing-workflows. What do you think? Also what about the default maven args - is this sensible default?

2021-10-11 01:52 UTC, olamy requested changes

2021-10-11 01:52 UTC, olamy commented on .github/maven.yml
> +      - name: Set up cache for ~./m2/repository
setup-java now have a cache (https://github.com/actions/setup-java#caching-maven-dependencies) maybe we can this step now.

2021-10-15 01:51 UTC, olamy commented
in wonder if we could use a strategy similar to this one https://github.com/apache/maven-gh-actions-shared
maybe with more default jdk distribution?

2021-10-15 03:05 UTC, merged

2021-10-17 12:17 UTC, plamentotev commented
> we can tag it and use the tag in components gh actions. so you can simply use only one project in a branch to test main. if we use tag then dependabot will propose the upgrade

Sounds great.

> in wonder if we could use a strategy similar to this one https://github.com/apache/maven-gh-actions-shared maybe with more default jdk distribution?

I didn't knew about this project. Looks interesting. You mean that we could use more flexible os/jdk matrix?